/**
 * ForgotPasswordPage
 * Step 1 — Enter email or phone to find account
 * Step 2 — Choose: set your own password OR use auto-generated
 * Rate-limited to once per day.
 */

import React, { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import {
  EnvelopeIcon,
  PhoneIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  ClockIcon,
  ArrowLeftIcon,
  EyeIcon,
  EyeSlashIcon,
  SparklesIcon,
  LockClosedIcon,
  ArrowPathIcon,
} from '@heroicons/react/24/outline';
import toast from 'react-hot-toast';
import apiClient from '../../api/axios';

const MODE_EMAIL = 'email';
const MODE_PHONE = 'phone';
const PW_AUTO   = 'auto';
const PW_CUSTOM = 'custom';

/* ── Letters-only password generator (mirrors backend logic) ── */
const UPPER = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
const LOWER = 'abcdefghjkmnpqrstuvwxyz';

const generatePreviewPassword = () => {
  const charset = UPPER + LOWER;
  let pw = '';
  for (let i = 0; i < 4; i++) {
    pw += UPPER[Math.floor(Math.random() * UPPER.length)];
    pw += LOWER[Math.floor(Math.random() * LOWER.length)];
  }
  for (let i = 0; i < 4; i++) {
    pw += charset[Math.floor(Math.random() * charset.length)];
  }
  return pw.split('').sort(() => Math.random() - 0.5).join('');
};

/* ── Spinner ── */
const Spinner = () => (
  <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
  </svg>
);

const ForgotPasswordPage = () => {
  /* ── Step 1 state ── */
  const [mode,       setMode]       = useState(MODE_EMAIL);
  const [identifier, setIdentifier] = useState('');
  const [step,       setStep]       = useState(1); // 1 = find account, 2 = choose password

  /* ── Step 2 state ── */
  const [pwMode,        setPwMode]        = useState(PW_AUTO);
  const [customPw,      setCustomPw]      = useState('');
  const [confirmPw,     setConfirmPw]     = useState('');
  const [showCustom,    setShowCustom]    = useState(false);
  const [showConfirm,   setShowConfirm]   = useState(false);
  const [previewPw,     setPreviewPw]     = useState(() => generatePreviewPassword());

  /* ── Shared state ── */
  const [loading,      setLoading]      = useState(false);
  const [stage,        setStage]        = useState('form'); // 'form' | 'success' | 'rate-limited'
  const [rateLimitMsg, setRateLimitMsg] = useState('');
  const [successMsg,   setSuccessMsg]   = useState('');
  const [autoGenerated, setAutoGenerated] = useState(false);

  const refreshPreview = useCallback(() => {
    setPreviewPw(generatePreviewPassword());
  }, []);

  /* ── Step 1: find account ── */
  const handleFindAccount = (e) => {
    e.preventDefault();
    if (!identifier.trim()) {
      toast.error(mode === MODE_EMAIL ? 'Please enter your email address' : 'Please enter your phone number');
      return;
    }
    setStep(2);
  };

  /* ── Step 2: submit reset ── */
  const handleReset = async (e) => {
    e.preventDefault();

    if (pwMode === PW_CUSTOM) {
      if (customPw.length < 6) {
        toast.error('Password must be at least 6 characters');
        return;
      }
      if (customPw !== confirmPw) {
        toast.error('Passwords do not match');
        return;
      }
    }

    setLoading(true);
    try {
      const payload = {
        identifier: identifier.trim(),
        ...(pwMode === PW_CUSTOM && { customPassword: customPw }),
      };

      const { data } = await apiClient.post('/auth/forgot-password', payload);

      if (data.success) {
        setSuccessMsg(data.message);
        setAutoGenerated(data.autoGenerated);
        setStage('success');
      }
    } catch (err) {
      const res = err.response?.data;
      if (res?.rateLimited) {
        setRateLimitMsg(res.message);
        setStage('rate-limited');
        return;
      }
      toast.error(res?.message || 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  /* ── Password strength indicator ── */
  const getStrength = (pw) => {
    if (!pw) return null;
    if (pw.length < 6)  return { label: 'Too short', color: 'bg-red-500',    width: 'w-1/4' };
    if (pw.length < 8)  return { label: 'Weak',      color: 'bg-orange-400', width: 'w-2/4' };
    if (pw.length < 12) return { label: 'Good',      color: 'bg-yellow-400', width: 'w-3/4' };
    return               { label: 'Strong',    color: 'bg-green-500',  width: 'w-full' };
  };
  const strength = getStrength(customPw);

  /* ════════════════════════════════════════════════════
     SUCCESS SCREEN
  ════════════════════════════════════════════════════ */
  if (stage === 'success') {
    return (
      <div className="min-h-[80vh] flex items-center justify-center px-4 py-12">
        <div className="w-full max-w-md text-center">
          <div className="w-20 h-20 bg-green-100 dark:bg-green-900/30 rounded-full
                          flex items-center justify-center mx-auto mb-6">
            <CheckCircleIcon className="w-10 h-10 text-green-600 dark:text-green-400" />
          </div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">
            Password Reset Successful
          </h1>
          <p className="text-gray-500 dark:text-gray-400 mb-4 leading-relaxed">
            {successMsg}
          </p>
          {autoGenerated && (
            <p className="text-gray-400 dark:text-gray-500 text-sm mb-6">
              Check your inbox for the new password. We recommend changing it after login.
            </p>
          )}
          <Link to="/login" className="btn-primary inline-block px-8 py-3 font-semibold">
            Go to Login
          </Link>
        </div>
      </div>
    );
  }

  /* ════════════════════════════════════════════════════
     RATE-LIMITED SCREEN
  ════════════════════════════════════════════════════ */
  if (stage === 'rate-limited') {
    return (
      <div className="min-h-[80vh] flex items-center justify-center px-4 py-12">
        <div className="w-full max-w-md">
          <div className="card p-8 text-center">
            <div className="w-16 h-16 bg-amber-100 dark:bg-amber-900/30 rounded-full
                            flex items-center justify-center mx-auto mb-5">
              <ClockIcon className="w-8 h-8 text-amber-600 dark:text-amber-400" />
            </div>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">
              Daily Limit Reached
            </h2>
            <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200
                            dark:border-amber-800 rounded-xl p-4 mb-6">
              <div className="flex items-start gap-3">
                <ExclamationTriangleIcon className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                <p className="text-amber-800 dark:text-amber-300 text-sm font-medium text-left">
                  {rateLimitMsg || 'You can use this option only once per day.'}
                </p>
              </div>
            </div>
            <p className="text-gray-500 dark:text-gray-400 text-sm mb-6">
              For security, password resets are limited to once every 24 hours.
            </p>
            <div className="flex flex-col gap-3">
              <button
                onClick={() => { setStage('form'); setStep(1); setIdentifier(''); }}
                className="btn-secondary w-full"
              >
                Try a Different Account
              </button>
              <Link to="/login" className="btn-primary w-full text-center py-2">
                Back to Login
              </Link>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ════════════════════════════════════════════════════
     STEP 1 — FIND ACCOUNT
  ════════════════════════════════════════════════════ */
  if (step === 1) {
    return (
      <div className="min-h-[80vh] flex items-center justify-center px-4 py-12">
        <div className="w-full max-w-md">
          <div className="text-center mb-8">
            <div className="w-14 h-14 bg-primary-100 dark:bg-primary-900/30 rounded-2xl
                            flex items-center justify-center mx-auto mb-4">
              <LockClosedIcon className="w-7 h-7 text-primary-600 dark:text-primary-400" />
            </div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Forgot Password?</h1>
            <p className="text-gray-500 dark:text-gray-400 mt-2 text-sm">
              Enter your registered email or phone number to get started.
            </p>
          </div>

          <div className="card p-8">
            {/* Email / Phone toggle */}
            <div className="flex rounded-xl border border-gray-200 dark:border-gray-700 p-1 mb-6">
              {[
                { id: MODE_EMAIL, label: 'Email',  icon: EnvelopeIcon },
                { id: MODE_PHONE, label: 'Phone',  icon: PhoneIcon    },
              ].map(({ id, label, icon: Icon }) => (
                <button
                  key={id}
                  type="button"
                  onClick={() => { setMode(id); setIdentifier(''); }}
                  className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg
                              text-sm font-medium transition-colors ${
                    mode === id
                      ? 'bg-primary-600 text-white'
                      : 'text-gray-600 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-700'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  {label}
                </button>
              ))}
            </div>

            <form onSubmit={handleFindAccount} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                  {mode === MODE_EMAIL ? 'Registered Email Address' : 'Registered Phone Number'}
                </label>
                <div className="relative">
                  {mode === MODE_EMAIL
                    ? <EnvelopeIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                    : <PhoneIcon    className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                  }
                  <input
                    type={mode === MODE_EMAIL ? 'email' : 'tel'}
                    value={identifier}
                    onChange={(e) => setIdentifier(e.target.value)}
                    placeholder={mode === MODE_EMAIL ? 'you@example.com' : '+91 98765 43210'}
                    className="input-field pl-9"
                    required
                  />
                </div>
              </div>

              <button type="submit" className="btn-primary w-full py-3 font-semibold">
                Continue →
              </button>
            </form>

            <div className="mt-5 text-center">
              <Link to="/login"
                className="inline-flex items-center gap-1.5 text-sm text-gray-500
                           dark:text-gray-400 hover:text-primary-600 transition-colors">
                <ArrowLeftIcon className="w-3.5 h-3.5" />
                Back to Login
              </Link>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ════════════════════════════════════════════════════
     STEP 2 — CHOOSE PASSWORD TYPE
  ════════════════════════════════════════════════════ */
  return (
    <div className="min-h-[80vh] flex items-center justify-center px-4 py-12">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Choose Your Password</h1>
          <p className="text-gray-500 dark:text-gray-400 mt-2 text-sm">
            Resetting password for <span className="font-medium text-primary-600 dark:text-primary-400">{identifier}</span>
          </p>
        </div>

        <div className="card p-8">
          {/* Password type selector */}
          <div className="grid grid-cols-2 gap-3 mb-6">
            {/* Auto-generated option */}
            <button
              type="button"
              onClick={() => setPwMode(PW_AUTO)}
              className={`relative flex flex-col items-center gap-2 p-4 rounded-xl border-2
                          transition-all text-center ${
                pwMode === PW_AUTO
                  ? 'border-primary-500 bg-primary-50 dark:bg-primary-900/20'
                  : 'border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600'
              }`}
            >
              {pwMode === PW_AUTO && (
                <span className="absolute top-2 right-2 w-4 h-4 bg-primary-600 rounded-full
                                 flex items-center justify-center text-white text-xs">✓</span>
              )}
              <SparklesIcon className={`w-7 h-7 ${pwMode === PW_AUTO ? 'text-primary-600' : 'text-gray-400'}`} />
              <div>
                <p className={`text-sm font-semibold ${pwMode === PW_AUTO ? 'text-primary-700 dark:text-primary-400' : 'text-gray-700 dark:text-gray-200'}`}>
                  Auto-Generate
                </p>
                <p className="text-xs text-gray-400 mt-0.5">Letters only, emailed to you</p>
              </div>
            </button>

            {/* Custom password option */}
            <button
              type="button"
              onClick={() => setPwMode(PW_CUSTOM)}
              className={`relative flex flex-col items-center gap-2 p-4 rounded-xl border-2
                          transition-all text-center ${
                pwMode === PW_CUSTOM
                  ? 'border-primary-500 bg-primary-50 dark:bg-primary-900/20'
                  : 'border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600'
              }`}
            >
              {pwMode === PW_CUSTOM && (
                <span className="absolute top-2 right-2 w-4 h-4 bg-primary-600 rounded-full
                                 flex items-center justify-center text-white text-xs">✓</span>
              )}
              <LockClosedIcon className={`w-7 h-7 ${pwMode === PW_CUSTOM ? 'text-primary-600' : 'text-gray-400'}`} />
              <div>
                <p className={`text-sm font-semibold ${pwMode === PW_CUSTOM ? 'text-primary-700 dark:text-primary-400' : 'text-gray-700 dark:text-gray-200'}`}>
                  Set My Own
                </p>
                <p className="text-xs text-gray-400 mt-0.5">Choose your own password</p>
              </div>
            </button>
          </div>

          <form onSubmit={handleReset} className="space-y-4">

            {/* ── AUTO-GENERATED preview ── */}
            {pwMode === PW_AUTO && (
              <div className="bg-gray-50 dark:bg-gray-700/50 rounded-xl p-4">
                <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-2">
                  Preview of auto-generated password:
                </p>
                <div className="flex items-center justify-between gap-3">
                  <span className="font-mono text-lg font-bold text-primary-600 dark:text-primary-400
                                   tracking-widest">
                    {previewPw}
                  </span>
                  <button
                    type="button"
                    onClick={refreshPreview}
                    className="p-1.5 rounded-lg text-gray-400 hover:text-primary-600
                               hover:bg-primary-50 dark:hover:bg-primary-900/20 transition-colors"
                    title="Generate another preview"
                  >
                    <ArrowPathIcon className="w-4 h-4" />
                  </button>
                </div>
                <p className="text-xs text-gray-400 mt-2">
                  ✉️ The actual password will be different and sent to your email.
                </p>
              </div>
            )}

            {/* ── CUSTOM password fields ── */}
            {pwMode === PW_CUSTOM && (
              <>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                    New Password
                  </label>
                  <div className="relative">
                    <input
                      type={showCustom ? 'text' : 'password'}
                      value={customPw}
                      onChange={(e) => setCustomPw(e.target.value)}
                      placeholder="Min. 6 characters"
                      className="input-field pr-10"
                      autoComplete="new-password"
                    />
                    <button
                      type="button"
                      onClick={() => setShowCustom(!showCustom)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                    >
                      {showCustom ? <EyeSlashIcon className="w-4 h-4" /> : <EyeIcon className="w-4 h-4" />}
                    </button>
                  </div>

                  {/* Strength bar */}
                  {customPw && strength && (
                    <div className="mt-2">
                      <div className="h-1.5 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                        <div className={`h-full rounded-full transition-all ${strength.color} ${strength.width}`} />
                      </div>
                      <p className={`text-xs mt-1 ${
                        strength.label === 'Strong' ? 'text-green-600' :
                        strength.label === 'Good'   ? 'text-yellow-600' : 'text-red-500'
                      }`}>
                        {strength.label}
                      </p>
                    </div>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
                    Confirm New Password
                  </label>
                  <div className="relative">
                    <input
                      type={showConfirm ? 'text' : 'password'}
                      value={confirmPw}
                      onChange={(e) => setConfirmPw(e.target.value)}
                      placeholder="Re-enter your password"
                      className={`input-field pr-10 ${
                        confirmPw && customPw !== confirmPw
                          ? 'border-red-400 focus:ring-red-400'
                          : confirmPw && customPw === confirmPw
                          ? 'border-green-400 focus:ring-green-400'
                          : ''
                      }`}
                      autoComplete="new-password"
                    />
                    <button
                      type="button"
                      onClick={() => setShowConfirm(!showConfirm)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                    >
                      {showConfirm ? <EyeSlashIcon className="w-4 h-4" /> : <EyeIcon className="w-4 h-4" />}
                    </button>
                  </div>
                  {confirmPw && customPw !== confirmPw && (
                    <p className="text-xs text-red-500 mt-1">Passwords do not match</p>
                  )}
                  {confirmPw && customPw === confirmPw && customPw.length >= 6 && (
                    <p className="text-xs text-green-600 mt-1">✓ Passwords match</p>
                  )}
                </div>
              </>
            )}

            {/* Once-per-day notice */}
            <div className="flex items-start gap-2 bg-amber-50 dark:bg-amber-900/20
                            border border-amber-200 dark:border-amber-800 rounded-lg px-3 py-2.5">
              <ExclamationTriangleIcon className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5" />
              <p className="text-amber-700 dark:text-amber-300 text-xs">
                This option is available <strong>once per day</strong> per account.
              </p>
            </div>

            <button
              type="submit"
              disabled={loading || (pwMode === PW_CUSTOM && (customPw.length < 6 || customPw !== confirmPw))}
              className="btn-primary w-full py-3 font-semibold"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <Spinner />
                  Resetting password...
                </span>
              ) : pwMode === PW_AUTO ? (
                '✉️ Generate & Email Password'
              ) : (
                '🔒 Set My Password'
              )}
            </button>
          </form>

          <div className="mt-4 flex items-center justify-between text-sm">
            <button
              onClick={() => setStep(1)}
              className="inline-flex items-center gap-1 text-gray-500 dark:text-gray-400
                         hover:text-primary-600 transition-colors"
            >
              <ArrowLeftIcon className="w-3.5 h-3.5" />
              Change account
            </button>
            <Link to="/login" className="text-gray-500 dark:text-gray-400 hover:text-primary-600 transition-colors">
              Back to Login
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ForgotPasswordPage;
